language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  # - nightly
notifications:
  email: false
script:
  - if [ -e .git/shallow ]; then git fetch --unshallow; fi
  - julia -e 'versioninfo()'
  - julia -e 'Pkg.clone("https://github.com/mauro3/Traits.jl"); Pkg.build("Traits")'
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Discretizations")'
  - julia -e 'Pkg.test("Discretizations", coverage=true)'
after_success:
  - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'cd(Pkg.dir("Discretizations")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
